//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eu.stork.peps.auth.engine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eIdentifier;givenName;surname;inheritedFamilyName;secondSurname;isdnie;adoptedFamilyName;gender;dateOfBirth;countryCodeOfBirth;nationalityCode;maritalStatus;textResidenceAddress;canonicalResidenceAddress;eMail;title;residencePermit;pseudonym;age;isAgeOver;signedDoc;citizenQAALevel;fiscalNumber")]
        public string PersonalAttributeList {
            get {
                return ((string)(this["PersonalAttributeList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/eIdentifier")]
        public string eIdentifier_NS {
            get {
                return ((string)(this["eIdentifier_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/givenName")]
        public string givenName_NS {
            get {
                return ((string)(this["givenName_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/surname")]
        public string surname_NS {
            get {
                return ((string)(this["surname_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/inheritedFamilyName")]
        public string inheritedFamilyName_NS {
            get {
                return ((string)(this["inheritedFamilyName_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/secondSurname")]
        public string secondSurname_NS {
            get {
                return ((string)(this["secondSurname_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/isdnie")]
        public string isdnie_NS {
            get {
                return ((string)(this["isdnie_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/adoptedFamilyName")]
        public string adoptedFamilyName_NS {
            get {
                return ((string)(this["adoptedFamilyName_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/gender")]
        public string gender_NS {
            get {
                return ((string)(this["gender_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/dateOfBirth")]
        public string dateOfBirth_NS {
            get {
                return ((string)(this["dateOfBirth_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/countryCodeOfBirth")]
        public string countryCodeOfBirth_NS {
            get {
                return ((string)(this["countryCodeOfBirth_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/nationalityCode")]
        public string nationalityCode_NS {
            get {
                return ((string)(this["nationalityCode_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/maritalStatus")]
        public string maritalStatus_NS {
            get {
                return ((string)(this["maritalStatus_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/textResidenceAddress")]
        public string textResidenceAddress_NS {
            get {
                return ((string)(this["textResidenceAddress_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/canonicalResidenceAddress")]
        public string canonicalResidenceAddress_NS {
            get {
                return ((string)(this["canonicalResidenceAddress_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/eMail")]
        public string eMail_NS {
            get {
                return ((string)(this["eMail_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/title")]
        public string title_NS {
            get {
                return ((string)(this["title_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/residencePermit")]
        public string residencePermit_NS {
            get {
                return ((string)(this["residencePermit_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/pseudonym")]
        public string pseudonym_NS {
            get {
                return ((string)(this["pseudonym_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/age")]
        public string age_NS {
            get {
                return ((string)(this["age_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/isAgeOver")]
        public string isAgeOver_NS {
            get {
                return ((string)(this["isAgeOver_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/signedDoc")]
        public string signedDoc_NS {
            get {
                return ((string)(this["signedDoc_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/citizenQAALevel")]
        public string citizenQAALevel_NS {
            get {
                return ((string)(this["citizenQAALevel_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/fiscalNumber")]
        public string fiscalNumber_NS {
            get {
                return ((string)(this["fiscalNumber_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/ocspResponse")]
        public string ocspResponse_NS {
            get {
                return ((string)(this["ocspResponse_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/forceAuth")]
        public string forceAuth_NS {
            get {
                return ((string)(this["forceAuth_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/registerType")]
        public string registerType_NS {
            get {
                return ((string)(this["registerType_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"surnameOfHolder;givenNameOfHolder;dateOfBirthOfHolder;studentIdentificationCode;nameOfQualification;nameOfTitle;mainFieldsOfStudy;nameOfAwardingInstitution;statusOfAwardingInstitution;languageOfInstruction;languageOfAssesment;levelOfQualification;officialLengthOfProgramme;accessRequirement;modeOfStudy;programmeRequirements;programmeDetails;gradingScheme;gradingDistributionGuidance;overallClassification;accessToFurtherStudy;professionalStatus;additionalInformation;additionalInformationSources;certificationDate;certificationCapacity;higherEducationSystemInformation;yearOfStudy;averageGradeOfStudy;studyRecommendation;isEligibleForInternship;isStudent;isAcademicStaff;isTeacherOf;isCourseCoordinator;isAdminStaff;habilitation;acTitle;hasDegree;hasAccountInBank;isHealthCareProfessional")]
        public string BusinessAttributeList {
            get {
                return ((string)(this["BusinessAttributeList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/surnameOfHolder")]
        public string surnameOfHolder_NS {
            get {
                return ((string)(this["surnameOfHolder_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/givenNameOfHolder")]
        public string givenNameOfHolder_NS {
            get {
                return ((string)(this["givenNameOfHolder_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/dateOfBirthOfHolder")]
        public string dateOfBirthOfHolder_NS {
            get {
                return ((string)(this["dateOfBirthOfHolder_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/studentIdentificationCode")]
        public string studentIdentificationCode_NS {
            get {
                return ((string)(this["studentIdentificationCode_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/nameOfQualification")]
        public string nameOfQualification_NS {
            get {
                return ((string)(this["nameOfQualification_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/nameOfTitle")]
        public string nameOfTitle_NS {
            get {
                return ((string)(this["nameOfTitle_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/mainFieldsOfStudy")]
        public string mainFieldsOfStudy_NS {
            get {
                return ((string)(this["mainFieldsOfStudy_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/nameOfAwardingInstitution")]
        public string nameOfAwardingInstitution_NS {
            get {
                return ((string)(this["nameOfAwardingInstitution_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/statusOfAwardingInstitution")]
        public string statusOfAwardingInstitution_NS {
            get {
                return ((string)(this["statusOfAwardingInstitution_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/languageOfInstruction")]
        public string languageOfInstruction_NS {
            get {
                return ((string)(this["languageOfInstruction_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/languageOfAssesment")]
        public string languageOfAssesment_NS {
            get {
                return ((string)(this["languageOfAssesment_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/levelOfQualification")]
        public string levelOfQualification_NS {
            get {
                return ((string)(this["levelOfQualification_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/officialLengthOfProgramme")]
        public string officialLengthOfProgramme_NS {
            get {
                return ((string)(this["officialLengthOfProgramme_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/accessRequirement")]
        public string accessRequirement_NS {
            get {
                return ((string)(this["accessRequirement_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/modeOfStudy")]
        public string modeOfStudy_NS {
            get {
                return ((string)(this["modeOfStudy_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/programmeRequirements")]
        public string programmeRequirements_NS {
            get {
                return ((string)(this["programmeRequirements_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/programmeDetails")]
        public string programmeDetails_NS {
            get {
                return ((string)(this["programmeDetails_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/gradingScheme")]
        public string gradingScheme_NS {
            get {
                return ((string)(this["gradingScheme_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/gradingDistributionGuidance")]
        public string gradingDistributionGuidance_NS {
            get {
                return ((string)(this["gradingDistributionGuidance_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/overallClassification")]
        public string overallClassification_NS {
            get {
                return ((string)(this["overallClassification_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/accessToFurtherStudy")]
        public string accessToFurtherStudy_NS {
            get {
                return ((string)(this["accessToFurtherStudy_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/professionalStatus")]
        public string professionalStatus_NS {
            get {
                return ((string)(this["professionalStatus_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/additionalInformation")]
        public string additionalInformation_NS {
            get {
                return ((string)(this["additionalInformation_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/additionalInformationSources")]
        public string additionalInformationSources_NS {
            get {
                return ((string)(this["additionalInformationSources_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/certificationDate")]
        public string certificationDate_NS {
            get {
                return ((string)(this["certificationDate_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/certificationCapacity")]
        public string certificationCapacity_NS {
            get {
                return ((string)(this["certificationCapacity_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/higherEducationSystemInformation")]
        public string higherEducationSystemInformation_NS {
            get {
                return ((string)(this["higherEducationSystemInformation_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/yearOfStudy")]
        public string yearOfStudy_NS {
            get {
                return ((string)(this["yearOfStudy_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/averageGradeOfStudy")]
        public string averageGradeOfStudy_NS {
            get {
                return ((string)(this["averageGradeOfStudy_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/studyRecommendation")]
        public string studyRecommendation_NS {
            get {
                return ((string)(this["studyRecommendation_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/isEligibleForInternship")]
        public string isEligibleForInternship_NS {
            get {
                return ((string)(this["isEligibleForInternship_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/isStudent")]
        public string isStudent_NS {
            get {
                return ((string)(this["isStudent_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/isAcademicStaff")]
        public string isAcademicStaff_NS {
            get {
                return ((string)(this["isAcademicStaff_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/isTeacherOf")]
        public string isTeacherOf_NS {
            get {
                return ((string)(this["isTeacherOf_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/isCourseCoordinator")]
        public string isCourseCoordinator_NS {
            get {
                return ((string)(this["isCourseCoordinator_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/isAdminStaff")]
        public string isAdminStaff_NS {
            get {
                return ((string)(this["isAdminStaff_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/habilitation")]
        public string habilitation_NS {
            get {
                return ((string)(this["habilitation_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/acTitle")]
        public string acTitle_NS {
            get {
                return ((string)(this["acTitle_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/hasDegree")]
        public string hasDegree_NS {
            get {
                return ((string)(this["hasDegree_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/hasAccountInBank")]
        public string hasAccountInBank_NS {
            get {
                return ((string)(this["hasAccountInBank_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/isHealthCareProfessional")]
        public string isHealthCareProfessional_NS {
            get {
                return ((string)(this["isHealthCareProfessional_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eLPIdentifier;legalName;alternativeName;type;translatableType;status;activity;reg" +
            "isteredAddress;registeredCanonicalAddress;contactInformation;fiscalNumber;repres" +
            "entative;represented;mandateContent")]
        public string LegalAttributeList {
            get {
                return ((string)(this["LegalAttributeList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/eLPIdentifier")]
        public string eLPIdentifier_NS {
            get {
                return ((string)(this["eLPIdentifier_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/legalName")]
        public string legalName_NS {
            get {
                return ((string)(this["legalName_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/alternativeName")]
        public string alternativeName_NS {
            get {
                return ((string)(this["alternativeName_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/type")]
        public string type_NS {
            get {
                return ((string)(this["type_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/translatableType")]
        public string translatableType_NS {
            get {
                return ((string)(this["translatableType_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/status")]
        public string status_NS {
            get {
                return ((string)(this["status_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/activity")]
        public string activity_NS {
            get {
                return ((string)(this["activity_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/registeredAddress")]
        public string registeredAddress_NS {
            get {
                return ((string)(this["registeredAddress_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/registeredCanonicalAddress")]
        public string registeredCanonicalAddress_NS {
            get {
                return ((string)(this["registeredCanonicalAddress_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/contactInformation")]
        public string contactInformation_NS {
            get {
                return ((string)(this["contactInformation_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/representative")]
        public string representative_NS {
            get {
                return ((string)(this["representative_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/represented")]
        public string represented_NS {
            get {
                return ((string)(this["represented_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.stork.gov.eu/1.0/mandateContent")]
        public string mandateContent_NS {
            get {
                return ((string)(this["mandateContent_NS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string AttributeSeparator {
            get {
                return ((string)(this["AttributeSeparator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string CountrySeparator {
            get {
                return ((string)(this["CountrySeparator"]));
            }
        }
    }
}
